-- Migration: 005_populate_categories
-- Origem: snapshot do banco em 2026-02-08
-- Objetivo: garantir lista completa de categorias no ambiente novo

insert into public.categories (name) values
  ('Adestrador'),
  ('Advogado'),
  ('Aluguel de Brinquedos'),
  ('Ar-condicionado'),
  ('Arquiteto'),
  ('Aulas de Informática'),
  ('Automação Residencial'),
  ('Azulejista'),
  ('Babá'),
  ('Banda para Festas'),
  ('Banho e Tosa'),
  ('Barbeiro'),
  ('Barman'),
  ('Bolo e Doces'),
  ('Buffet'),
  ('Cabeleireira'),
  ('Calheiro'),
  ('Cerimonialista'),
  ('Chaveiro'),
  ('Chaveiro 24h'),
  ('Confeiteira'),
  ('Consultor Financeiro'),
  ('Contador'),
  ('Costureira'),
  ('Cozinheira'),
  ('Criação de Sites'),
  ('Cuidador de Idosos'),
  ('Decorador'),
  ('Decorador de Festas'),
  ('Dedetizador'),
  ('Depiladora'),
  ('Desentupidor'),
  ('Desenvolvedor Mobile'),
  ('Desenvolvedor Web'),
  ('Designer de Sobrancelhas'),
  ('Designer Gráfico'),
  ('Detetive Particular'),
  ('Diarista'),
  ('DJ'),
  ('Editor de Vídeo'),
  ('Eletricista'),
  ('Eletricista de Autos'),
  ('Empregada Doméstica'),
  ('Encanador'),
  ('Enfermeira'),
  ('Engenheiro Civil'),
  ('Entregador'),
  ('Esteticista'),
  ('Filmagem de Eventos'),
  ('Fisioterapeuta'),
  ('Fonoaudiólogo'),
  ('Fotógrafo'),
  ('Funilaria e Pintura'),
  ('Garçom'),
  ('Gesseiro'),
  ('Gestor de Tráfego'),
  ('Guincho'),
  ('Hospedagem Pet'),
  ('Impermeabilizador'),
  ('Instalação de Redes'),
  ('Instalação de Som Automotivo'),
  ('Instalador de Piso'),
  ('Instrutor de Yoga'),
  ('Jardineiro'),
  ('Lavadeira'),
  ('Lavagem Automotiva'),
  ('Limpeza de Estofados'),
  ('Limpeza Pós-Obra'),
  ('Manicure e Pedicure'),
  ('Maquiadora'),
  ('Marceneiro'),
  ('Marido de Aluguel'),
  ('Marketing Digital'),
  ('Martelinho de Ouro'),
  ('Massagista'),
  ('Mecânico Automotivo'),
  ('Mecânico de Motos'),
  ('Mestre de Obras'),
  ('Micropigmentadora'),
  ('Montador de móveis'),
  ('Motoboy'),
  ('Motorista Particular'),
  ('Mudanças e Carretos'),
  ('Nutricionista'),
  ('Organizador Pessoal'),
  ('Paisagista'),
  ('Passadeira'),
  ('Passeador de Cães'),
  ('Pedreiro'),
  ('Personal Trainer'),
  ('Pintor'),
  ('Piscineiro'),
  ('Podóloga'),
  ('Professor de Dança'),
  ('Professor de Espanhol'),
  ('Professor de Inglês'),
  ('Professor de Matemática'),
  ('Professor de Música'),
  ('Professor de Piano'),
  ('Professor de Português'),
  ('Professor de Violão'),
  ('Psicólogo'),
  ('Recuperação de Dados'),
  ('Redator'),
  ('Reforço Escolar'),
  ('Salgados para Festas'),
  ('Sapateiro'),
  ('Segurança de Eventos'),
  ('Segurança Eletrônica'),
  ('SEO'),
  ('Serralheiro'),
  ('Social Media'),
  ('Tapeceiro'),
  ('Técnico de Celular'),
  ('Técnico de informática'),
  ('Telhadista'),
  ('Terapeuta Holístico'),
  ('Tradutor'),
  ('UI/UX Designer'),
  ('Veterinário em Domicílio'),
  ('Vidraceiro')
on conflict (name) do nothing;

